django_clones/social_clone/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'signup/$', views.SignUp.as_view(), name='signup'),
]

django_clones/social_clone/posts/urls.py
from django.conf.urls import url

from . import views

app_name='posts'

urlpatterns = [
    url(r'^$', views.PostList.as_view(), name='all'),
    url(r'^new/$', views.PostCreate.as_view(), name='create'),
    url(r'^by/(?P<username>[-\w]+)$', views.UserPosts.as_view(), name='for_user'),
    url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.PostDetail.as_view(), name='single'),
    url(r'^delete/(?P<pk>\d+)/$', views.DeletePost.as_view(), name='delete'),
]

django_clones/social_clone/social_clone/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

from social_clone import settings
from .views import HomePage, TestPage, ThanksPage

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', HomePage.as_view(), name='home'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^groups/', include('groups.urls', namespace='groups')),
    url(r'^test/$', TestPage.as_view(), name='test'),
    url(r'^thanks/$', ThanksPage.as_view(), name='thanks'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

django_clones/social_clone/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Star Social</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'clone/css/master.css' %}">

</head>
<body>

<nav class="navbar mynav" role="navigation" id="navbar">
    <div class="container">
        <a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>

        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a href="{% url 'posts:create' %}">Post</a></li>
                <li><a href="{% url 'groups:all' %}">Groups</a></li>
                <li><a href="{% url 'groups:create' %}">Create Group</a></li>
                <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
            {% else %}
                <li><a href="{% url 'groups:all' %}">Groups</a></li>
                <li><a href="{% url 'accounts:login' %}">Log In</a></li>
                <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container mycontent">

    {% block body %}

    {% endblock %}

</div>
<canvas id="canvas"></canvas>
</body>
<script src="{% static 'clone/js/master.js' %}" type="text/javascript" ></script>

</html>

django_clones/social_clone/templates/index.html
{% extends "base.html" %}

{% block body %}
    <h1>Welcome to StarSocial!</h1>
{% endblock %}

django_clones/social_clone/templates/test.html
{% extends 'base.html' %}

{% block body%}
<h1>Logged in</h1>
{% endblock %}

django_clones/social_clone/templates/thanks.html
{% extends 'base.html' %}

{% block body %}
<h1>Thank you for visiting, come back soon!</h1>
{% endblock %}